Update branch-protection.yaml

diff --git a/.github/workflows/branch-protection.yaml b/.github/workflows/branch-protection.yaml
--- a/.github/workflows/branch-protection.yaml
+++ b/.github/workflows/branch-protection.yaml
@@ -21,13 +21,20 @@ jobs:
       if: github.event_name == 'push'
       run: |
         git fetch origin  # Fetch the latest state of all branches.
-        # Check if the last commit is a merge commit from staging to main
+        # Check if the last commit is a merge commit
+        PARENTS_COUNT=$(git cat-file -p HEAD | grep -c parent)
+        if [[ "$PARENTS_COUNT" -lt 2 ]]; then
+          echo "Error: Direct pushes to main should be merge commits from the staging branch."
+          exit 1
+        fi
+        # Check if the merge commit is from staging to main
         PARENT_COMMIT=$(git rev-parse HEAD^2)
         STAGING_COMMIT=$(git rev-parse origin/staging)
         if [[ "$PARENT_COMMIT" != "$STAGING_COMMIT" ]]; then
           echo "Error: Direct pushes to main are only allowed from the staging branch."
           exit 1
         fi
+
 
     - name: Check PR source branch
       if: github.event_name == 'pull_request'
